AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI-powered Software Development Agentic System (Serverless Only)

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref DataTable
        S3_BUCKET_NAME: !Ref CodeBucket
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: INFO
        POWERTOOLS_SERVICE_NAME: agenticai
    Tracing: Active
    Layers:
      - !Ref SharedLayer

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

  BudgetAlertEmail:
    Type: String
    Description: Email address for budget alerts
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$

  AdminEmail:
    Type: String
    Description: Email address for operational alerts (errors, performance issues)
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$

Resources:
  # --- STORAGE ---
  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub agenticai-code-${AWS::AccountId}-${Environment}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub agenticai-data-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # --- MESSAGING (SQS) ---
  PMQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub agenticai-pm-queue-${Environment}
      VisibilityTimeout: 360
      MessageRetentionPeriod: 345600

  DevQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub agenticai-dev-queue-${Environment}
      VisibilityTimeout: 960
      MessageRetentionPeriod: 345600

  QAQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub agenticai-qa-queue-${Environment}
      VisibilityTimeout: 660
      MessageRetentionPeriod: 345600

  OpsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub agenticai-ops-queue-${Environment}
      VisibilityTimeout: 360
      MessageRetentionPeriod: 345600

  # --- LAMBDA LAYER ---
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.13
    Properties:
      LayerName: !Sub agenticai-shared-${Environment}
      ContentUri: lambda/shared/
      CompatibleRuntimes:
        - python3.13

  # --- IAM ROLES ---
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub agenticai-lambda-role-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess

  # --- FUNCTIONS ---
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agenticai-api-handler-${Environment}
      CodeUri: lambda/api_handler/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SQS_QUEUE_URL_PM: !Ref PMQueue
          SQS_QUEUE_URL_DEV: !Ref DevQueue
          SQS_QUEUE_URL_QA: !Ref QAQueue
          SQS_QUEUE_URL_OPS: !Ref OpsQueue
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref RestApi
            Auth:
              ApiKeyRequired: true

  PMAgentWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agenticai-pm-agent-${Environment}
      CodeUri: lambda/pm_agent/
      Handler: worker.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PMQueue.Arn
            BatchSize: 1

  DevAgentWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agenticai-dev-agent-${Environment}
      CodeUri: lambda/dev_agent/
      Handler: worker.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 900
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt DevQueue.Arn
            BatchSize: 1

  QAAgentWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agenticai-qa-agent-${Environment}
      CodeUri: lambda/qa_agent/
      Handler: worker.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 600
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt QAQueue.Arn
            BatchSize: 1

  OpsAgentWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agenticai-ops-agent-${Environment}
      CodeUri: lambda/ops_agent/
      Handler: worker.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OpsQueue.Arn
            BatchSize: 1

  # --- API GATEWAY ---
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"

  # API Key for authentication
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub agenticai-api-key-${Environment}
      Description: API Key for AgenticAI API access
      Enabled: true
      StageKeys:
        - RestApiId: !Ref RestApi
          StageName: prod

  # Usage Plan with rate limiting
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub agenticai-usage-plan-${Environment}
      Description: Usage plan with rate limiting for AgenticAI API
      ApiStages:
        - ApiId: !Ref RestApi
          Stage: prod
      Throttle:
        RateLimit: 1000
        BurstLimit: 2000
      Quota:
        Limit: 1000
        Period: DAY

  # Associate API Key with Usage Plan
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  # Store API Key in Parameter Store
  ApiKeyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /agenticai/${Environment}/api-key
      Description: API Key for AgenticAI API access
      Type: String
      Value: !Ref ApiKey

  # --- ALERTING (SNS) ---
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub agenticai-alerts-${Environment}
      DisplayName: AgenticAI Production Alerts
      Subscription:
        - Endpoint: !Ref AdminEmail
          Protocol: email

  # --- CLOUDWATCH ALARMS ---
  # Lambda Error Rate Alarm
  LambdaErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub agenticai-lambda-error-rate-${Environment}
      AlarmDescription: Lambda error rate exceeded 5% over 5 minutes
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: FunctionName
          Value: !Ref ApiHandler

  # Lambda Consecutive Failures Alarm (API Handler)
  ApiHandlerConsecutiveFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub agenticai-api-handler-consecutive-failures-${Environment}
      AlarmDescription: API Handler Lambda failed 3 consecutive times
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 3
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: FunctionName
          Value: !Ref ApiHandler

  # Lambda Consecutive Failures Alarm (PM Agent)
  PMAgentConsecutiveFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub agenticai-pm-agent-consecutive-failures-${Environment}
      AlarmDescription: PM Agent Lambda failed 3 consecutive times
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 3
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: FunctionName
          Value: !Ref PMAgentWorker

  # Lambda Consecutive Failures Alarm (Dev Agent)
  DevAgentConsecutiveFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub agenticai-dev-agent-consecutive-failures-${Environment}
      AlarmDescription: Dev Agent Lambda failed 3 consecutive times
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 3
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: FunctionName
          Value: !Ref DevAgentWorker

  # Lambda Consecutive Failures Alarm (QA Agent)
  QAAgentConsecutiveFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub agenticai-qa-agent-consecutive-failures-${Environment}
      AlarmDescription: QA Agent Lambda failed 3 consecutive times
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 3
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: FunctionName
          Value: !Ref QAAgentWorker

  # Lambda Consecutive Failures Alarm (Ops Agent)
  OpsAgentConsecutiveFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub agenticai-ops-agent-consecutive-failures-${Environment}
      AlarmDescription: Ops Agent Lambda failed 3 consecutive times
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 3
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: FunctionName
          Value: !Ref OpsAgentWorker

  # API Gateway 5XX Error Alarm
  ApiGateway5XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub agenticai-api-gateway-5xx-errors-${Environment}
      AlarmDescription: API Gateway 5XX errors exceeded 10 over 5 minutes
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: ApiName
          Value: !Ref RestApi

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint

  DataTableName:
    Description: "DynamoDB table name"
    Value: !Ref DataTable
    Export:
      Name: !Sub ${AWS::StackName}-DataTableName

  DataTableArn:
    Description: "DynamoDB table ARN"
    Value: !GetAtt DataTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DataTableArn

  CodeBucketName:
    Description: "S3 bucket for generated code"
    Value: !Ref CodeBucket
    Export:
      Name: !Sub ${AWS::StackName}-CodeBucketName

  PMQueueUrl:
    Description: "PM Agent SQS Queue URL"
    Value: !Ref PMQueue
    Export:
      Name: !Sub ${AWS::StackName}-PMQueueUrl

  DevQueueUrl:
    Description: "Dev Agent SQS Queue URL"
    Value: !Ref DevQueue
    Export:
      Name: !Sub ${AWS::StackName}-DevQueueUrl

  QAQueueUrl:
    Description: "QA Agent SQS Queue URL"
    Value: !Ref QAQueue
    Export:
      Name: !Sub ${AWS::StackName}-QAQueueUrl

  OpsQueueUrl:
    Description: "Ops Agent SQS Queue URL"
    Value: !Ref OpsQueue
    Export:
      Name: !Sub ${AWS::StackName}-OpsQueueUrl

  AlertTopicArn:
    Description: "SNS Topic ARN for alerts"
    Value: !Ref AlertTopic
    Export:
      Name: !Sub ${AWS::StackName}-AlertTopicArn

  ApiKeyId:
    Description: "API Key ID for authentication"
    Value: !Ref ApiKey
    Export:
      Name: !Sub ${AWS::StackName}-ApiKeyId

  UsagePlanId:
    Description: "Usage Plan ID"
    Value: !Ref UsagePlan
    Export:
      Name: !Sub ${AWS::StackName}-UsagePlanId